### ISSUE TITLE
before_last not called  

### ISSUE THREAD

**Issue by pimo** [GittiHab/One-Menu#1]
Hello!

I installed One menu on a One Cms fresh install and i can't view the menu.

I red the instruction and the php code and i can't find the before_last function in any file.

Is there a issue or do i made a mistake?

thanks

**Comment by GittiHab** [comment]
@pimo You are right. `before_last` has been missing in the GitHub Version. I have updated the `/lib/one.php/` file – try replacing it and see if it works.

**Comment by pimo** [comment]
It works but On fresh installation the menu appears before the tag 
`<p class="last">// That was the document hello2</p>`

is it right?
I expected the menu after the tag

thanks

**Comment by GittiHab** [comment]
Hey @pimo,
You are in fact right. That's why the hook is called `**before**_last`. I have pushed another version with the new hook `after_last`. If you now change the function `before_last` to `after_last` in `one_menu.php:40` everything should be like you expected.
